# Generated by Django 5.1.1 on 2025-06-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_tipocliente_tipomaterial_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='fecha_entrada',
            field=models.DateField(),
        ),
    ]
