# Generated by Django 5.2.3 on 2025-06-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_alter_material_fecha_entrada"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoVestimenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Tipo de Vestimenta",
                "verbose_name_plural": "Tipos de Vestimentas",
                "db_table": "tipos_vestimentas",
            },
        ),
    ]
