# Generated by Django 5.2.3 on 2025-06-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0004_tipovestimenta"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Tipo de Pedido",
                "verbose_name_plural": "Tipos de Pedidos",
                "db_table": "tipos_pedidos",
            },
        ),
    ]
