# Generated by Django 5.2.3 on 2025-06-16 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0006_producto_pedido_venta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vestimenta",
            name="cliente",
        ),
        migrations.AddField(
            model_name="cliente",
            name="tipo_cliente",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="productos.tipocliente",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vestimenta",
            name="tipo_vestimenta",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="productos.tipovestimenta",
            ),
            preserve_default=False,
        ),
    ]
