# Generated by Django 5.1.1 on 2025-06-16 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_remove_vestimenta_cliente_cliente_tipo_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='vestimenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.vestimenta'),
        ),
    ]
